#ifndef __RCC_TGMATH_H
#define __RCC_TGMATH_H

#include <math.h>
#include <complex.h>

#define acos(x) __builtin_tgmath_acos((x))
#define asin(x) __builtin_tgmath_asin((x))
#define atan(x) __builtin_tgmath_atan((x))
#define acosh(x) __builtin_tgmath_acosh((x))
#define asinh(x) __builtin_tgmath_asinh((x))
#define atanh(x) __builtin_tgmath_atanh((x))
#define cos(x) __builtin_tgmath_cos((x))
#define sin(x) __builtin_tgmath_sin((x))
#define tan(x) __builtin_tgmath_tan((x))
#define cosh(x) __builtin_tgmath_cosh((x))
#define sinh(x) __builtin_tgmath_sinh((x))
#define tanh(x) __builtin_tgmath_tanh((x))
#define exp(x) __builtin_tgmath_exp((x))
#define log(x) __builtin_tgmath_log((x))
#define sqrt(x) __builtin_tgmath_sqrt((x))
#define fabs(x) __builtin_tgmath_fabs((x))

#define atan2(x, y) __builtin_tgmath_atan2((x), (y))
#define pow(x, y) __builtin_tgmath_pow((x), (y))

#define cbrt(x) __builtin_tgmath_cbrt((x))
#define ceil(x) __builtin_tgmath_ceil((x))
#define copysign(x, y) __builtin_tgmath_copysign((x), (y))
#define erf(x) __builtin_tgmath_erf((x))
#define erfc(x) __builtin_tgmath_erfc((x))
#define exp2(x) __builtin_tgmath_exp2((x))
#define expm1(x) __builtin_tgmath_expm1((x))
#define fdim(x, y) __builtin_tgmath_fdim((x), (y))
#define floor(x) __builtin_tgmath_floor((x))
#define fma(x, y, z) __builtin_tgmath_fma((x), (y), (z))
#define fmax(x, y) __builtin_tgmath_fmax((x), (y))
#define fmin(x, y) __builtin_tgmath_fmin((x), (y))
#define fmod(x, y) __builtin_tgmath_fmod((x), (y))
#define frexp(x, y) __builtin_tgmath_frexp((x), (y))
#define hypot(x, y) __builtin_tgmath_hypot((x), (y))
#define ilogb(x) __builtin_tgmath_ilogb((x))
#define ldexp(x, y) __builtin_tgmath_ldexp((x), (y))
#define lgamma(x) __builtin_tgmath_lgamma((x))
#define llrint(x) __builtin_tgmath_llrint((x))
#define llround(x) __builtin_tgmath_llround((x))
#define log10(x) __builtin_tgmath_log10((x))
#define log1p(x) __builtin_tgmath_log1p((x))
#define log2(x) __builtin_tgmath_log2((x))
#define logb(x) __builtin_tgmath_logb((x))
#define lrint(x) __builtin_tgmath_lrint((x))
#define lround(x) __builtin_tgmath_lround((x))
#define modf(x, y) __builtin_tgmath_modf((x), (y))
#define nearbyint(x) __builtin_tgmath_nearbyint((x))
#define nextafter(x, y) __builtin_tgmath_nextafter((x), (y))
#define nexttoward(x, y) __builtin_tgmath_nexttoward((x), (y))
#define remainder(x, y) __builtin_tgmath_remainder((x), (y))
#define remquo(x, y, z) __builtin_tgmath_remquo((x), (y), (z))
#define rint(x) __builtin_tgmath_rint((x))
#define round(x) __builtin_tgmath_round((x))
#define scalbn(x, y) __builtin_tgmath_scalbn((x), (y))
#define scalbln(x, y) __builtin_tgmath_scalbln((x), (y))
#define tgamma(x) __builtin_tgmath_tgamma((x))
#define trunc(x) __builtin_tgmath_trunc((x))

#define carg(x) __builtin_tgmath_carg((x))
#define cimag(x) __builtin_tgmath_cimag((x))
#define conj(x) __builtin_tgmath_conj((x))
#define cproj(x) __builtin_tgmath_cproj((x))
#define creal(x) __builtin_tgmath_creal((x))

#endif
